version: '2.2'

# mostly extending from main .yml
services:
  www:
    environment:
    - DESECSTACK_E2E_TEST=TRUE # increase abuse limits and such
    volumes:
    - autocert:/autocert/

  api:
    environment:
    - DESECSTACK_E2E_TEST=TRUE # increase abuse limits and such

  nslord:
    networks:
      front:
        ipv4_address: ${DESECSTACK_IPV4_REAR_PREFIX16}.0.129 # make nslord available for test-e2e
    environment:
    - DESECSTACK_NSLORD_CACHE_TTL=0

  test-e2e2:
    build: test/e2e2
    restart: "no"
    environment:
    - DESECSTACK_DOMAIN
    - DESECSTACK_NS
    - DESECSTACK_IPV4_REAR_PREFIX16
    - DESECSTACK_IPV6_SUBNET
    - DESECSTACK_IPV6_ADDRESS
    - DESECSTACK_NSLORD_DEFAULT_TTL
    volumes:
    - autocert:/autocert/:ro
    mac_address: 06:42:ac:10:00:7f
    depends_on:
    - www
    - nslord
    - nsmaster
    networks:
      front:
        ipv4_address: ${DESECSTACK_IPV4_REAR_PREFIX16}.0.127
    extra_hosts:
    - "checkipv4.dedyn.${DESECSTACK_DOMAIN}:${DESECSTACK_IPV4_REAR_PREFIX16}.0.128"
    - "checkipv6.dedyn.${DESECSTACK_DOMAIN}:${DESECSTACK_IPV4_REAR_PREFIX16}.0.128"
    - "checkip.dedyn.${DESECSTACK_DOMAIN}:${DESECSTACK_IPV4_REAR_PREFIX16}.0.128"
    - "dedyn.${DESECSTACK_DOMAIN}:${DESECSTACK_IPV4_REAR_PREFIX16}.0.128"
    - "desec.${DESECSTACK_DOMAIN}:${DESECSTACK_IPV4_REAR_PREFIX16}.0.128"
    - "update6.dedyn.${DESECSTACK_DOMAIN}:${DESECSTACK_IPV4_REAR_PREFIX16}.0.128"
    - "update.dedyn.${DESECSTACK_DOMAIN}:${DESECSTACK_IPV4_REAR_PREFIX16}.0.128"
    - "www.dedyn.${DESECSTACK_DOMAIN}:${DESECSTACK_IPV4_REAR_PREFIX16}.0.128"
    - "www.desec.${DESECSTACK_DOMAIN}:${DESECSTACK_IPV4_REAR_PREFIX16}.0.128"
    - "get.desec.${DESECSTACK_DOMAIN}:${DESECSTACK_IPV4_REAR_PREFIX16}.0.128"

volumes:
  autocert:
